### ISSUE TITLE
Johnson and Bickel rules work for normalized (out of 1) datasets, but does not calculate correctly for others

### ISSUE THREAD

**Issue by brentkaplan** [miyamot0/discountingtools#2]
https://github.com/miyamot0/discountingtools/blob/d9a30d515adc35990eb9bb523c84451c4fb4c93a/R/score.R#L881-L891

Instead of .2 for JB1 and .1 for JB2, I believe they should be (1.2*LL) and (1.1*LL) and the function would need to pass through or otherwise identify what the LL is.

**Comment by miyamot0** [comment]
This was addressed in the re-write. References to the LL shouldn't be necessary here because the input was assumed to be normalized to a max of 1 (i.e., undiscounted value). The earlier program assumed this, but the revised algorithm forces the user to specify their max/undiscounted value and this is carried forward towards this check.
